#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDL8iMpoqjySiz+ygIk82GMhYw03pYS9wlevYY0tiAV6jcoFrDxOWRitBDbohGP5YkQQqVLaNvfkjHsHnyFeeB6OOL6iBivBFPUAv4cAjDrDy31076ip9Ae0PJQib/WJQ11hQL5cLj9QYLUA7QWx/9/BpVt4/PU1BeWcHK/AzdVbZlkYQZbhhzd+WK+ZXYkHdiEKbYABEea6v2NdSz0Gxt4cCBX0xLHynMRjY9TfiKdVo4iOBB1lizMSm92ey0ccN+WrvV+EL+hQgsEx9YR+8NvETJcm5M43/vS6ADMlz6262oOjsvHLUWms3L180FBOxeQSF4yUkcPN9fKtm6mDOR
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD

package_update: true
packages:
  - mariadb-server
  - mariadb-client

runcmd:
  - systemctl enable --now mariadb
  - mariadb -e "CREATE DATABASE IF NOT EXISTS webdb;"
  - mariadb -e "CREATE USER IF NOT EXISTS 'webuser'@'%' IDENTIFIED BY 'webpass';"
  - mariadb -e "GRANT ALL PRIVILEGES ON webdb.* TO 'webuser'@'%'; FLUSH PRIVILEGES;"
  - sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  - systemctl restart mariadb
